export {default as Home} from './Home/Home'
export {default as Chat} from './Chat/Chat'
export {default as FindTalent} from './FindTalent/FindTalent'
export {default as LoginSignup} from './LogInAndSignUp/LoginSignUp'
export {default as FindWork} from './FindWork/FindWork'
