export { default as Home } from "./Home/Home";
export { default as Chat } from "./Chat/Chat";
export { default as FindTalent } from "./FindTalent/FindTalent";
export { default as LoginSignup } from "./LogInAndSignUp/LoginSignUp";
export { default as FindWork } from "./FindWork/FindWork";
export { default as FindPartner } from "./FindPartner/FindPartner";
export { default as UserProfile } from "./UserProfile/UserProfile";
export { default as PostWork } from "./PostWork/PostWork";
export { default as FreelancerProfile } from "./FreelancerProfile/FreelancerProfile";
export { default as Bid } from "./Bid/Bid";
export { default as ClientDashboard } from "./ClientDashboard/ClientDashboard";
export { default as AllWorks } from "./AllWorks/AllWorks";
export { default as AllPosts } from "./AllPosts/AllPosts";
export { default as ClientProjectProgress } from "./ClientProjectProgress/ClientProjectProgress";
export { default as EditProfile } from "./EditProfile/EditProfile";
export { default as EditProfileInfo } from "../components/EditProfileInfo/EditProfileInfo";
export { default as EditBasicInfo } from "../components/EditBasicInfo/EditBasicInfo";
export { default as EditUsername } from "../components/EditUsername/EditUsername";
export { default as WebsiteFeedback } from "./WebsiteFeedback/WebsiteFeedback"
